# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Corne Choc Pro Gallium'
on:
  push:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corne_choc_pro_left","corne_choc_pro_right"]'
      shield: '["nice_view_adapter nice_view_gem"]'
      alphas: '["gallium"]'
      extra: '["qwerty"]'
      tap: '["gallium"]'
      modules: '["M165437/nice-view-gem/v0.3.0"]'
